name: deploy to Google Cloud Run

on:

  workflow_run:
    workflows: ["3MTT App CI"]
    types:
     - completed

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_CREDENTIALS}}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: 'auth'
        name: Configure GCP credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          token_format: 'access_token'

      - name: Log in to GCR
        uses: docker/login-action@v1
        with:
          registry: us-docker.pkg.dev
          # username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS }}
          
      - name: Build and Push Docker image to GCR
        run: |
          docker build -t us-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push us-docker.pkg.dev/${{ env.PROJECT_ID }}/Y${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      
      - name: Deploy to Cloud Run
        run: |
          terraform init -input=true
          terraform state list
          terraform plan -var="image_tag=${{ github.sha }}"
          terraform apply \
          -var="project_id=${{ env.PROJECT_ID }}"\
          -var="repo_name=${{ env.REPO_NAME }}"\
          -var="location=${{ env.LOCATION }}"\
          -var="image_name=${{ env.IMAGE_NAME }}"\
          -var="image_tag=${{ env.github.sha }}"\          
          -auto-approve
