name: deploy to Ec2

on:
    # pull_request:
    #     branches: ["Main"]
  workflow_run:
    workflows: ["3MTT App CI"]
    types:
     - completed

jobs:
    deploy-ec2-terraform:
    # needs: [deploy-to-dockerHub]
      runs-on: ubuntu-latest

      steps:
        
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Configure SSH Key
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/id_rsa/app-ssh-key.pem
          chmod 600 ~/.ssh/id_rsa
          echo "Private key configured"

      - name: Terraform Apply
        id:   apply
        env:
          TF_VAR_ec2_name:  "${{ github.event.inputs.ec2-name }}"
        run: |
          cd tf-example/
          terraform init
          terraform validate
          terraform plan 
          terraform apply -auto-approve
