name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches: 
      ["Main"] # Trigger on pushes to the main branch

env:
  PROJECT_ID: ${{ vars.PROJECT_ID }} # Update with your Google Cloud project ID
  REGION: ${{ vars.LOCATION }} # Update with your region
  SERVICE: 'capstone-repo' # Update with your service name

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'

    steps:
      - name: 'Checkout Source Code'
        uses: actions/checkout@v4

      - name: 'Authenticate with Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set Up gcloud CLI'
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: '${{ env.PROJECT_ID }}'

      # Build and push the Docker image to Google Artifact Registry
      - name: 'Build and Push Docker Image'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:latest"
          echo "Building Docker image..."
          docker build -t "${DOCKER_TAG}" .
          echo "Authenticating Docker with gcloud..."
          gcloud auth configure-docker "${{ env.REGION }}-docker.pkg.dev" --quiet
          echo "Pushing Docker image to Artifact Registry..."
          docker push "${DOCKER_TAG}"

      # Deploy the container to Cloud Run
      - name: 'Deploy to Cloud Run'
        run: |-
          echo "Deploying to Cloud Run..."
          gcloud run deploy "${{ env.SERVICE }}" \
            --image "us-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:latest"\
            --region "${{ env.REGION }}" \
            --allow-unauthenticated \
            --quiet

      # Output the Cloud Run URL
      - name: 'Show Cloud Run URL'
        run: |-
          SERVICE_URL=$(gcloud run services describe "${{ env.SERVICE }}" --region "${{ env.REGION }}" --format 'value(status.url)')
          echo "Cloud Run service deployed at: $SERVICE_URL"
